# -*- coding: utf-8 -*-
"""NeuroGAN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FqX1HYwW7F0NS7r2E53e3Knn_7a0V9JP

# Task
Load the Parquet Files

## Load the specified parquet file

### Subtask:
Convert from bytes to pixel brightness

**Reasoning**:
Update the file path in the existing code cell to load the specified parquet file and execute the cell.

## Inspect the dataframe

### Subtask:
Save to pandas df

**Reasoning**:
Display the column names, data types, and first few rows of the DataFrame to understand its structure and the nature of the image data.

## Extract and display images

### Subtask:
Based on the DataFrame structure, write code to extract the image data (e.g., if it's in a specific column) and display the images. This might require using libraries like Pillow or OpenCV.

**Reasoning**:
Import PIL and iterate through the first few rows of the dataframe to extract and display the images.
"""

# Ensure pyarrow is installed in this kernel
!pip install --quiet pyarrow
!pip install pandas Pillow kagglehub ipywidgets numpy matplotlib pyarrow

import pandas as pd
from PIL import Image
import io
import numpy as np
import os
import pandas as pd
import pyarrow.parquet as pq
import pyarrow as pa
import matplotlib.pyplot as plt

# Load parquet files
# Make sure to reference download instructions. You have to download the kaggle dataset and upload it, rename it to a data directory. Video guide coming soon
#from: https://drive.google.com/drive/folders/12-1XR8df-rYkwJuMqMgXYQ9dm6EoDx0f?usp=drive_link
#quickstart guide: https://www.youtube.com/watch?v=WPRarAeelAM
#Original source + description: https://advp.niagads.org/downloads
train_df = pd.read_parquet("train.parquet")
test_df  = pd.read_parquet("test.parquet")

def bytes_to_pixels(b: bytes) -> np.ndarray:
    """
    Convert raw image bytes (e.g. JPEG/PNG) into a 2D numpy array of pixel values (grayscale).
    """
    img = Image.open(io.BytesIO(b))  # convert to grayscale
    return np.array(img)
def extract_bytes(blob):
    """
    Unwrap a dict‐wrapped binary payload if needed,
    otherwise return blob directly.
    """
    if isinstance(blob, dict):
        # try common keys
        for key in ("bytes", "data", "image"):
            if key in blob and isinstance(blob[key], (bytes, bytearray)):
                return blob[key]
        # fallback: first bytes‐like value
        for v in blob.values():
            if isinstance(v, (bytes, bytearray)):
                return v
        raise TypeError(f"No bytes found in dict payload: {list(blob.keys())}")
    return blob

train_df["image"] = train_df["image"].apply(lambda blob: bytes_to_pixels(extract_bytes(blob)))
test_df["image"]  = test_df["image"].apply(lambda blob: bytes_to_pixels(extract_bytes(blob)))

def display_images(df, n=10):
    """
    Display the first n grayscale images (numpy arrays) from df
    along with their labels. Assumes df has columns 'image' and 'label'.
    """
    for i, (_, row) in enumerate(df.head(n).iterrows(), start=1):
        pixels = row["image"]
        label = row.get("label", "")
        # Create a PIL image in 'L' mode (8-bit pixels, black and white)
        img = Image.fromarray(pixels.astype("uint8"), mode="L")
        print(f"{i}. label = {label}")
        display(img)
display_images(train_df)

"""# Task
Identify the minority class in the `train_df` dataset, then filter `train_df` to retain only the images from this minority class. Subsequently, resize these minority class images to 64x64 pixels and normalize their pixel values to the range of [-1, 1]. Finally, verify the preprocessing by displaying a sample of these images, along with their labels, and confirm their shape and pixel value range to ensure they are ready for use in a dataloader.

## Identify Minority Class

### Subtask:
Analyze the distribution of labels in the `train_df` to identify the minority class. This will involve counting occurrences of each unique label.

**Reasoning**:
To identify the minority class, I will calculate the frequency of each unique label in the 'label' column of `train_df`, then find the label with the minimum count and store it in `minority_class_label`.
"""

label_counts = train_df['label'].value_counts()
minority_class_label = label_counts.idxmin()
print(f"Label distribution:\n{label_counts}")
print(f"\nThe minority class is: {minority_class_label}")

"""## Filter Minority Class Images

### Subtask:
Filter the `train_df` to create a new DataFrame that contains only the images and their corresponding labels for the identified minority class.

**Reasoning**:
To filter `train_df` for the minority class, I will select rows where the 'label' column matches the previously identified `minority_class_label` and store the result in a new DataFrame called `minority_class_df`.
"""

minority_class_df = train_df[train_df['label'] == minority_class_label]
print(f"Minority class DataFrame shape: {minority_class_df.shape}")
print("First 5 rows of minority_class_df:")
print(minority_class_df.head())

"""## Resize and Normalize Images

### Subtask:
Iterate through the filtered minority class images. For each image, resize it to 64x64 pixels and then normalize its pixel values to the range of [-1, 1].

**Reasoning**:
I will initialize an empty list, iterate through each image in the 'image' column of `minority_class_df`, convert it to a PIL Image, resize it to 64x64, convert it back to a NumPy array, normalize its pixel values to [-1, 1], append it to the list, and finally update the 'image' column in `minority_class_df`.
"""

preprocessed_images_list = []

for image_array in minority_class_df['image']:
    # Convert NumPy array to PIL Image
    img = Image.fromarray(image_array.astype('uint8'), mode='L')

    # Resize the image to 64x64 pixels
    resized_img = img.resize((64, 64))

    # Convert resized PIL Image back to NumPy array
    resized_image_array = np.array(resized_img)

    # Normalize pixel values to [-1, 1]
    normalized_image_array = (resized_image_array / 127.5) - 1

    preprocessed_images_list.append(normalized_image_array)

# Update the 'image' column in minority_class_df with the preprocessed images
minority_class_df['image'] = preprocessed_images_list

print(f"Successfully resized and normalized {len(preprocessed_images_list)} images.")

"""**Reasoning**:
The previous code produced a `SettingWithCopyWarning` because `minority_class_df` was a view of `train_df`. To prevent this, I will ensure `minority_class_df` is an independent copy by using `.copy()` when filtering.


"""

minority_class_df = train_df[train_df['label'] == minority_class_label].copy()
print(f"Minority class DataFrame shape: {minority_class_df.shape}")
print("First 5 rows of minority_class_df:")
print(minority_class_df.head())

"""**Reasoning**:
Now that `minority_class_df` is an independent copy, I will re-run the image resizing and normalization steps to ensure the changes are applied correctly without warnings, following the instructions to convert to PIL, resize, convert back to NumPy, and normalize.


"""

preprocessed_images_list = []

for image_array in minority_class_df['image']:
    # Convert NumPy array to PIL Image
    img = Image.fromarray(image_array.astype('uint8'), mode='L')

    # Resize the image to 64x64 pixels
    resized_img = img.resize((64, 64))

    # Convert resized PIL Image back to NumPy array
    resized_image_array = np.array(resized_img)

    # Normalize pixel values to [-1, 1]
    normalized_image_array = (resized_image_array / 127.5) - 1

    preprocessed_images_list.append(normalized_image_array)

# Update the 'image' column in minority_class_df with the preprocessed images
minority_class_df['image'] = preprocessed_images_list

print(f"Successfully resized and normalized {len(preprocessed_images_list)} images.")

"""**Reasoning**:
Now that the images in `minority_class_df` have been resized and normalized, I need to verify the preprocessing by displaying a sample of these images, along with their labels, and confirm their shape and pixel value range to ensure they are ready for use in a dataloader.


"""

def display_preprocessed_images(df, n=5):
    """
    Display the first n preprocessed grayscale images (numpy arrays) from df
    along with their labels. Assumes df has columns 'image' and 'label',
    and images are normalized to [-1, 1].
    """
    print(f"Displaying first {n} preprocessed images and verifying properties...")
    for i, (_, row) in enumerate(df.head(n).iterrows()):
        pixels = row["image"]
        label = row.get("label", "")

        # Denormalize for display (from [-1, 1] to [0, 255])
        display_pixels = ((pixels + 1) * 127.5).astype('uint8')
        img = Image.fromarray(display_pixels, mode="L")

        print(f"--- Image {i+1} ---")
        print(f"Label: {label}")
        print(f"Shape: {pixels.shape}")
        print(f"Min pixel value: {pixels.min():.2f}")
        print(f"Max pixel value: {pixels.max():.2f}")
        display(img)

display_preprocessed_images(minority_class_df)

"""**Reasoning**:
The previous code generated a `DeprecationWarning` regarding the `mode` parameter in `Image.fromarray()`. To address this, I will remove the `mode='L'` argument, as `Image.fromarray()` can infer the correct mode for grayscale images from the NumPy array's data type.


"""

def display_preprocessed_images(df, n=5):
    """
    Display the first n preprocessed grayscale images (numpy arrays) from df
    along with their labels. Assumes df has columns 'image' and 'label',
    and images are normalized to [-1, 1].
    """
    print(f"Displaying first {n} preprocessed images and verifying properties...")
    for i, (_, row) in enumerate(df.head(n).iterrows()):
        pixels = row["image"]
        label = row.get("label", "")

        # Denormalize for display (from [-1, 1] to [0, 255])
        display_pixels = ((pixels + 1) * 127.5).astype('uint8')
        # Removed mode='L' as it is deprecated
        img = Image.fromarray(display_pixels)

        print(f"--- Image {i+1} ---")
        print(f"Label: {label}")
        print(f"Shape: {pixels.shape}")
        print(f"Min pixel value: {pixels.min():.2f}")
        print(f"Max pixel value: {pixels.max():.2f}")
        display(img)

display_preprocessed_images(minority_class_df)

"""## Final Task

### Subtask:
Confirm that the dataset has been successfully loaded, pre-processed, and filtered to contain only the minority class images, resized to 64x64, and normalized to [-1, 1], ready for use in a dataloader.

## Summary:

### Q&A
Yes, the dataset has been successfully pre-processed and filtered. It now contains only the minority class images, which have been resized to 64x64 pixels and normalized to the range of [-1, 1]. This dataset is ready for use in a dataloader.

### Data Analysis Key Findings
*   The minority class in the `train_df` dataset was identified as label '1', with a total of 49 occurrences. The full label distribution was: '2' (2566), '3' (1781), '0' (724), and '1' (49).
*   A new DataFrame, `minority_class_df`, was successfully created, containing only the 49 images and their labels for the minority class '1'.
*   All 49 minority class images were successfully resized to 64x64 pixels and their pixel values were normalized to the range of [-1, 1].
*   During the process, a `SettingWithCopyWarning` was encountered and resolved by explicitly creating a copy of the DataFrame. A `DeprecationWarning` related to `mode='L'` in `Image.fromarray()` was also resolved by removing the deprecated parameter, allowing proper inference of the image mode.
*   Verification confirmed that the preprocessed images have the expected shape of (64, 64) and pixel values are correctly within the \[-1, 1] range.

### Insights or Next Steps
*   The preprocessed minority class dataset is now in an optimal state for use in a PyTorch or TensorFlow `DataLoader` for tasks such as training a generative model (e.g., GANs or VAEs) focused on minority class samples.
*   Consider applying similar preprocessing steps consistently across all datasets (training, validation, test) to ensure uniformity if they are to be used with the same model architecture.
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
import torchvision.utils as vutils
import matplotlib.pyplot as plt
import numpy as np
import random
import os

# Set a random seed for reproducibility (CRITICAL for hackathon scoring)
# Replace YOUR_SEED with any number.
YOUR_SEED = 42
random.seed(YOUR_SEED)
torch.manual_seed(YOUR_SEED)
torch.cuda.manual_seed_all(YOUR_SEED)

# Check for GPU
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# --- 1. GAN Configuration and Architecture ---
# Hyperparameters for the DCGAN architecture
nz = 100    # Size of the "latent z-vector" (random noise input)
ngf = 64    # Size of feature maps in generator
ndf = 64    # Size of feature maps in discriminator
nc = 1      # Number of channels (1 for Grayscale MRI)
lr = 0.0002 # Learning rate for Adam
beta1 = 0.5 # Beta1 hyperparameter for Adam

class Generator(nn.Module):
    """
    The Generator network (The Forger). Takes noise and outputs a fake 64x64 MRI image.
    """
    def __init__(self):
        super(Generator, self).__init__()
        self.main = nn.Sequential(
            # Input is Z (noise vector)
            nn.ConvTranspose2d(nz, ngf * 8, 4, 1, 0, bias=False),
            nn.BatchNorm2d(ngf * 8),
            nn.ReLU(True),
            # State size: (ngf*8) x 4 x 4

            nn.ConvTranspose2d(ngf * 8, ngf * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 4),
            nn.ReLU(True),
            # State size: (ngf*4) x 8 x 8

            nn.ConvTranspose2d(ngf * 4, ngf * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 2),
            nn.ReLU(True),
            # State size: (ngf*2) x 16 x 16

            nn.ConvTranspose2d(ngf * 2, ngf, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf),
            nn.ReLU(True),
            # State size: (ngf) x 32 x 32

            nn.ConvTranspose2d(ngf, nc, 4, 2, 1, bias=False),
            nn.Tanh() # Output image normalized to [-1, 1]
            # Final State size: (nc) x 64 x 64
        )

    def forward(self, input):
        return self.main(input)

class Discriminator(nn.Module):
    """
    The Discriminator network (The Detective). Classifies image as Real (1) or Fake (0).
    """
    def __init__(self):
        super(Discriminator, self).__init__()
        self.main = nn.Sequential(
            # Input is (nc) x 64 x 64
            nn.Conv2d(nc, ndf, 4, 2, 1, bias=False),
            nn.LeakyReLU(0.2, inplace=True),
            # State size: (ndf) x 32 x 32

            nn.Conv2d(ndf, ndf * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ndf * 2),
            nn.LeakyReLU(0.2, inplace=True),
            # State size: (ndf*2) x 16 x 16

            nn.Conv2d(ndf * 2, ndf * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ndf * 4),
            nn.LeakyReLU(0.2, inplace=True),
            # State size: (ndf*4) x 8 x 8

            nn.Conv2d(ndf * 4, ndf * 8, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ndf * 8),
            nn.LeakyReLU(0.2, inplace=True),
            # State size: (ndf*8) x 4 x 4

            nn.Conv2d(ndf * 8, 1, 4, 1, 0, bias=False),
            nn.Sigmoid() # Output a single probability (0 or 1)
        )

    def forward(self, input):
        return self.main(input).view(-1, 1).squeeze(1)


# Initialize G and D
netG = Generator().to(device)
netD = Discriminator().to(device)

# Initialize BCELoss function
criterion = nn.BCELoss()

# Establish convention for real and fake labels
real_label = 1.
fake_label = 0.

# Setup Adam optimizers
optimizerD = optim.Adam(netD.parameters(), lr=lr, betas=(beta1, 0.999))
optimizerG = optim.Adam(netG.parameters(), lr=lr, betas=(beta1, 0.999))

# --- Custom Dataset for preprocessed images ---
class MinorityClassDataset(torch.utils.data.Dataset):
    def __init__(self, dataframe):
        self.images = dataframe['image'].tolist()
        self.labels = dataframe['label'].tolist()

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        image = self.images[idx]
        # Convert numpy array to torch tensor, add channel dimension, and ensure float type
        image_tensor = torch.from_numpy(image).float().unsqueeze(0)
        label = self.labels[idx]
        return image_tensor, label

# Instantiate the custom dataset and dataloader
minority_dataset = MinorityClassDataset(minority_class_df)
batch_size = 32 # You can adjust this batch size
dataloader = torch.utils.data.DataLoader(minority_dataset, batch_size=batch_size, shuffle=True)


# ==============================================================================
# --- 2. Training Loop ---
# NOTE: The 'dataloader' variable must be defined here, loaded with the minority class.
# Example:
# dataloader = torch.utils.data.DataLoader(dataset, batch_size=64, shuffle=True)
# ==============================================================================
def train_gan(netG, netD, dataloader, num_epochs=50):
    """Runs the alternating training loop for the Generator and Discriminator."""
    G_losses = []
    D_losses = []
    fixed_noise = torch.randn(64, nz, 1, 1, device=device)
    img_list = [] # Initialize img_list here for logging generated images

    print("Starting GAN Training Loop...")

    for epoch in range(num_epochs):
        for i, data in enumerate(dataloader, 0):

            ############################
            # (1) Update D network: Maximize log(D(x)) + log(1 - D(G(z)))
            ###########################
            netD.zero_grad()
            real_cpu = data[0].to(device) # data[0] contains images, data[1] contains labels
            b_size = real_cpu.size(0)

            # Train with all-real batch
            label_real = torch.full((b_size,), real_label, dtype=torch.float, device=device)
            output = netD(real_cpu)
            errD_real = criterion(output, label_real)
            errD_real.backward()
            D_x = output.mean().item()

            # Train with all-fake batch
            noise = torch.randn(b_size, nz, 1, 1, device=device)
            fake = netG(noise)
            label_fake = torch.full((b_size,), fake_label, dtype=torch.float, device=device)
            output = netD(fake.detach()) # .detach() prevents G from training
            errD_fake = criterion(output, label_fake)
            errD_fake.backward()
            D_G_z1 = output.mean().item()

            # Combine loss and update D
            errD = errD_real + errD_fake
            optimizerD.step()

            ############################
            # (2) Update G network: Maximize log(D(G(z)))
            ###########################
            netG.zero_grad()
            # Generator wants fake images to be classified as real
            label_G = torch.full((b_size,), real_label, dtype=torch.float, device=device)
            output = netD(fake) # Use the fake batch from before
            errG = criterion(output, label_G)
            errG.backward()
            D_G_z2 = output.mean().item()

            # Update G
            optimizerG.step()

            # Print training stats
            if i % 100 == 0:
                print(f'[{epoch+1}/{num_epochs}][{i}/{len(dataloader)}]	Loss_D: {errD.item():.4f}\tLoss_G: {errG.item():.4f}\tD(x): {D_x:.4f}\tD(G(z)): {D_G_z1:.4f} / {D_G_z2:.4f}')

            G_losses.append(errG.item())
            D_losses.append(errD.item())

        # Save visual progress (first batch of fakes)
        with torch.no_grad():
            img_list.append(vutils.make_grid(netG(fixed_noise).detach().cpu(), padding=2, normalize=True))

    print("GAN Training Finished.")
    return G_losses, D_losses, img_list, fixed_noise # Return fixed_noise as well for visualization

# Run the training loop with the minority class dataloader
num_gan_epochs = 50 # You can adjust the number of epochs
G_losses, D_losses, img_list, fixed_noise = train_gan(netG, netD, dataloader, num_epochs=num_gan_epochs)


# ==============================================================================
# --- 3. Visualization and Data Generation ---
# These functions are executed after successful GAN training.
# ==============================================================================

def visualize_comparison(netG, dataloader, fixed_noise):
    """
    Creates the Real vs. Synthetic comparison plot for the report.
    """
    plt.figure(figsize=(10, 5))

    # Plot Real Images (Left)
    real_batch = next(iter(dataloader))
    plt.subplot(1, 2, 1)
    plt.axis("off")
    plt.title("Real MRI Scans (Minority Class)")
    plt.imshow(np.transpose(vutils.make_grid(real_batch[0].to(device)[:32], padding=5, normalize=True).cpu(),(1,2,0)))

    # Plot Fake Images (Right)
    with torch.no_grad():
        fake_display = netG(fixed_noise).detach().cpu()

    plt.subplot(1, 2, 2)
    plt.axis("off")
    plt.title("Synthetic MRI Scans (NeuroGAN)")
    # We denormalize the images for proper display from the [-1, 1] Tanh range
    plt.imshow(np.transpose(vutils.make_grid(fake_display[:32], padding=5, normalize=True, value_range=(-1, 1)), (1,2,0)))

    plt.suptitle("NeuroGAN: Real vs. Synthetic Data Quality Check")
    plt.savefig("real_vs_fake_comparison.png", bbox_inches='tight')
    plt.show()
    print("Comparison image saved as 'real_vs_fake_comparison.png'")

def generate_and_save_synthetic_data(netG, num_images_to_generate=1000, batch_size=64):
    """
    Generates a large batch of synthetic images and saves them to a folder.
    This data is then used to augment the training dataset for the final classifier.
    """
    output_folder = "synthetic_data/ModerateDemented_Synth"
    os.makedirs(output_folder, exist_ok=True)
    print(f"Created folder: {output_folder}")

    count = 0
    with torch.no_grad():
        while count < num_images_to_generate:
            current_batch_size = min(batch_size, num_images_to_generate - count)
            # Generate random noise
            noise = torch.randn(current_batch_size, nz, 1, 1, device=device)

            # Generate fake images
            fake_images = netG(noise)

            # Save each image individually
            for i in range(current_batch_size):
                file_name = f"{output_folder}/synth_{count + i:04d}.png"
                # Saves image, normalizing the Tanh output [-1, 1] to a displayable [0, 1]
                vutils.save_image(fake_images[i], file_name, normalize=True, value_range=(-1, 1))

            count += current_batch_size

            if count % 200 == 0:
                print(f"Generated {count}/{num_images_to_generate} images...")

    print("Synthetic dataset creation complete.")
    print(f"Total images generated: {num_images_to_generate}")

# Run the generation and visualization
# 1. Visualize the output
visualize_comparison(netG, dataloader, fixed_noise)
# 2. Generate and save the final dataset
generate_and_save_synthetic_data(netG, num_images_to_generate=1000)

"""## Zip Synthetic Data Folder

### Subtask:
Create a zip archive of the `synthetic_data` folder.

**Reasoning**:
I will use Python's `zipfile` module to compress the `synthetic_data` folder into a zip file, making it easy to download or share.
"""

import os
import zipfile

output_zip_filename = 'synthetic_data.zip'
synthetic_data_folder = 'synthetic_data'

with zipfile.ZipFile(output_zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files in os.walk(synthetic_data_folder):
        for file in files:
            file_path = os.path.join(root, file)
            # Add file to zip, preserving directory structure within the zip
            zipf.write(file_path, os.path.relpath(file_path, os.path.dirname(synthetic_data_folder)))

print(f"Successfully zipped '{synthetic_data_folder}' to '{output_zip_filename}'.")

"""## Save Data Analysis Findings to File

### Subtask:
Consolidate and save all key findings and insights from the data analysis, CNN model training, and confusion matrix evaluation into a markdown file.

**Reasoning**:
I will combine the summaries from previous steps into a single string and then write this string to a markdown file named `data_analysis_findings.md`.
"""

findings_content = """
# Data Analysis Findings

## Combined Data Preprocessing and GAN Augmentation Summary
### Q&A
Yes, the dataset has been successfully pre-processed and filtered. It now contains only the minority class images, which have been resized to 64x64 pixels and normalized to the range of [-1, 1]. This dataset is ready for use in a dataloader.

### Data Analysis Key Findings
*   The minority class in the `train_df` dataset was identified as label '1', with a total of 49 occurrences. The full label distribution was: '2' (2566), '3' (1781), '0' (724), and '1' (49).
*   A new DataFrame, `minority_class_df`, was successfully created, containing only the 49 images and their labels for the minority class '1'.
*   All 49 minority class images were successfully resized to 64x64 pixels and their pixel values were normalized to the range of [-1, 1].
*   During the process, a `SettingWithCopyWarning` was encountered and resolved by explicitly creating a copy of the DataFrame. A `DeprecationWarning` related to `mode='L'` in `Image.fromarray()` was also resolved by removing the deprecated parameter, allowing proper inference of the image mode.
*   Verification confirmed that the preprocessed images have the expected shape of (64, 64) and pixel values are correctly within the [-1, 1] range.

### Insights or Next Steps
*   The preprocessed minority class dataset is now in an optimal state for use in a PyTorch or TensorFlow `DataLoader` for tasks such as training a generative model (e.g., GANs or VAEs) focused on minority class samples.
*   Consider applying similar preprocessing steps consistently across all datasets (training, validation, test) to ensure uniformity if they are to be used with the same model architecture.

## CNN Model Training and Evaluation Results on Combined Dataset
### Q&A
The training and evaluation results of the CNN model on the combined dataset show an overall accuracy of 95.26% and an overall weighted F1-score of 95.28%. Performance varies slightly across classes, with Class 1 achieving a perfect 1.00 F1-score, while Class 0 has the lowest F1-score at 0.91.

### Data Analysis Key Findings
*   The CNN model was trained over 10 epochs. The training loss consistently decreased from approximately 0.8346 (Epoch 1) to 0.0521 (Epoch 10).
*   Validation accuracy improved significantly throughout training, starting at 63.73% (Epoch 1) and reaching a peak of 95.26% by Epoch 10.
*   The final evaluation on the validation set showed an overall accuracy of 0.9526 (95.26%) and an overall weighted F1-score of 0.9528 (95.28%).
*   Class-wise performance from the classification report indicates:
    *   **Class 1** demonstrated exceptional performance with a Precision, Recall, and F1-score of 1.00.
    *   **Class 2** and **Class 3** also performed very well, with F1-scores of 0.96 and 0.94, respectively.
    *   **Class 0** had slightly lower performance compared to others, with an F1-score of 0.91 (Precision: 0.88, Recall: 0.94).

### Insights or Next Steps
*   The model demonstrates strong classification capabilities for the given dataset, with high overall accuracy and F1-score.
*   Investigate the samples belonging to Class 0 to understand potential reasons for its slightly lower performance compared to other classes. This could involve reviewing image quality, feature commonality, or potential mislabeling within this specific class.

## Confusion Matrix Insights
### Q&A
The confusion matrix reveals strong classification performance overall. Class 1 (Minority Class) shows exceptional performance with 198 correct predictions out of 198 actual instances, indicating no misclassifications. Class 2 correctly predicted 505 instances, with minor misclassifications to Class 0 (9) and Class 3 (16). Similarly, Class 3 made 327 correct predictions, with 9 misclassified as Class 0 and 15 as Class 2. The main area for improvement is Class 0, where 136 instances were correctly identified, but 4 were misclassified as Class 2 and 5 as Class 3, which is relatively significant given its class size.

### Data Analysis Key Findings
*   A confusion matrix was successfully generated and displayed, visualizing the CNN model's classification performance.
*   The model exhibited strong performance for Class 1 (Minority Class), with 198 out of 198 instances correctly classified and no misclassifications.
*   For Class 2, the model achieved 505 correct predictions, with only 9 instances misclassified as Class 0 and 16 as Class 3.
*   Class 3 showed 327 correct predictions, with 9 instances misclassified as Class 0 and 15 as Class 2.
*   Class 0 was identified as the primary area for improvement, with 136 correct predictions but 4 misclassified as Class 2 and 5 as Class 3, suggesting some challenges for this class.

### Insights or Next Steps
*   The successful classification of Class 1 (Minority Class) with no errors highlights the effectiveness of the GAN-based data augmentation in balancing this class and improving the model's ability to learn its distinct features.
*   Further investigation into the misclassifications for Class 0 could involve analyzing the features of the misclassified instances to understand common patterns or similarities with other classes, potentially leading to targeted feature engineering or additional data augmentation for this specific class.
"""

with open("data_analysis_findings.md", "w") as f:
    f.write(findings_content)

print("Data analysis findings saved to data_analysis_findings.md")

"""## Combine Original Data with Synthetic Data

### Subtask:
Create a new dataset that contains all original data from `train_df` and all generated synthetic data for the minority class. Ensure all images are pre-processed (resized to 64x64 and normalized to [-1, 1]).

**Reasoning**:
I will load each synthetic image, preprocess it (resize and normalize), and then store it along with the `minority_class_label` in a new DataFrame. Finally, I'll concatenate this synthetic DataFrame with the original `train_df` to create the complete combined dataset. Note that the original `train_df` already contains `minority_class_df` within it, but the images in `train_df` are not yet resized and normalized like the `minority_class_df` (which is already resized and normalized). Therefore, we will preprocess all images before combining them.
"""

import os
import numpy as np
import pandas as pd
from PIL import Image
import torch

# Define the folder where synthetic images are saved
synthetic_data_folder = "synthetic_data/ModerateDemented_Synth"

synthetic_images_data = []

# Loop through each synthetic image file
for filename in os.listdir(synthetic_data_folder):
    if filename.endswith(".png"):
        img_path = os.path.join(synthetic_data_folder, filename)
        img = Image.open(img_path).convert('L') # Open as grayscale

        # Resize to 64x64 (already done during generation, but good to ensure consistency)
        resized_img = img.resize((64, 64))

        # Convert to numpy array
        img_array = np.array(resized_img)

        # Normalize to [-1, 1]
        normalized_img_array = (img_array / 127.5) - 1

        synthetic_images_data.append({"image": normalized_img_array, "label": minority_class_label})

# Create a DataFrame for synthetic data
synthetic_df = pd.DataFrame(synthetic_images_data)

print(f"Loaded {len(synthetic_df)} synthetic images.")

# Preprocess the entire original train_df to ensure all images are 64x64 and normalized
# This is necessary because train_df's 'image' column still contains original sized images.
preprocessed_train_images = []

for image_array in train_df['image']:
    # Convert NumPy array to PIL Image
    img = Image.fromarray(image_array.astype('uint8')) # Removed mode='L' as it is deprecated

    # Resize the image to 64x64 pixels
    resized_img = img.resize((64, 64))

    # Convert resized PIL Image back to NumPy array
    resized_image_array = np.array(resized_img)

    # Normalize pixel values to [-1, 1]
    normalized_image_array = (resized_image_array / 127.5) - 1

    preprocessed_train_images.append(normalized_image_array)

# Create a temporary DataFrame with preprocessed original images and their labels
preprocessed_train_df = pd.DataFrame({
    'image': preprocessed_train_images,
    'label': train_df['label'].values
})

print(f"Preprocessed {len(preprocessed_train_df)} original images.")

# Combine the preprocessed original data and synthetic data
combined_df = pd.concat([preprocessed_train_df, synthetic_df], ignore_index=True)

print(f"Combined dataset shape: {combined_df.shape}")
print("Combined dataset label distribution:")
print(combined_df['label'].value_counts())

# Verify a sample from the combined_df (similar to display_preprocessed_images)
def display_combined_images(df, n=5):
    print(f"Displaying first {n} combined images and verifying properties...")
    for i, (_, row) in enumerate(df.head(n).iterrows()):
        pixels = row["image"]
        label = row.get("label", "")
        display_pixels = ((pixels + 1) * 127.5).astype('uint8')
        img = Image.fromarray(display_pixels) # Removed mode='L' as it is deprecated

        print(f"--- Image {i+1} ---")
        print(f"Label: {label}")
        print(f"Shape: {pixels.shape}")
        print(f"Min pixel value: {pixels.min():.2f}")
        print(f"Max pixel value: {pixels.max():.2f}")
        display(img)

display_combined_images(combined_df)

"""# Task
Create PyTorch Dataset and DataLoader instances from the `combined_df`. Split the `combined_df` into training and validation sets (e.g., 80% training, 20% validation) and create a `Dataset` and `DataLoader` for each split. Ensure the `Dataset` class properly handles the image data (NumPy arrays) and labels, preparing them for batching and feeding into a CNN model during training and evaluation.

## Create PyTorch Dataset and DataLoader from Combined Data

### Subtask:
Convert the `combined_df` into a PyTorch Dataset and DataLoader. This will involve handling the image data (numpy arrays) and labels for batching and feeding into the CNN during training and evaluation.

**Reasoning**:
First, I will import the necessary libraries, including `torch`, `Dataset`, `DataLoader`, and `train_test_split`, to prepare for creating the custom PyTorch dataset and data loaders.
"""

import torch
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
import numpy as np

"""**Reasoning**:
Now that the libraries are imported, I will define a custom PyTorch `Dataset` class called `CustomImageDataset` to handle the images and labels from the `combined_df` for batching.


"""

class CustomImageDataset(Dataset):
    def __init__(self, dataframe):
        self.images = dataframe['image'].tolist()
        self.labels = dataframe['label'].tolist()

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        image = self.images[idx]
        label = self.labels[idx]
        # Convert numpy array to torch tensor, add channel dimension, and ensure float type
        # Grayscale images (H, W) need to be (C, H, W) where C=1
        image_tensor = torch.from_numpy(image).float().unsqueeze(0)
        return image_tensor, label

"""**Reasoning**:
Now that the `CustomImageDataset` class is defined, I will split the `combined_df` into training and validation sets using `train_test_split` to prepare data for training and evaluation.


"""

train_df_split, val_df_split = train_test_split(combined_df, test_size=0.2, random_state=YOUR_SEED)

print(f"Training set size: {len(train_df_split)}")
print(f"Validation set size: {len(val_df_split)}")

# Instantiate the custom dataset for both splits
train_dataset = CustomImageDataset(train_df_split)
val_dataset = CustomImageDataset(val_df_split)

# Create PyTorch DataLoader instances
batch_size = 32 # Can be adjusted based on memory and performance needs
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

print(f"Train DataLoader has {len(train_dataloader)} batches of size {batch_size}")
print(f"Validation DataLoader has {len(val_dataloader)} batches of size {batch_size}")

"""## Define a Simple CNN Model

### Subtask:
Define a custom simple Convolutional Neural Network (CNN) architecture. This model will be designed to handle 64x64 grayscale images and output classifications for the four labels present in the dataset.

**Reasoning**:
To define the custom CNN model, I will start by importing `torch.nn` and then create a `SimpleCNN` class that inherits from `nn.Module`. I will define convolutional layers, activation functions, pooling layers, and fully connected layers in the `__init__` method, and implement the forward pass in the `forward` method.
"""

import torch.nn as nn
import torch.nn.functional as F

class SimpleCNN(nn.Module):
    def __init__(self, num_classes=4):
        super(SimpleCNN, self).__init__()
        # Input: 1 channel (grayscale), 64x64 image
        # Convolutional Layer 1
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=32, kernel_size=3, stride=1, padding=1)
        # After conv1: (32, 64, 64)
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)
        # After pool1: (32, 32, 32)

        # Convolutional Layer 2
        self.conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, stride=1, padding=1)
        # After conv2: (64, 32, 32)
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)
        # After pool2: (64, 16, 16)

        # Convolutional Layer 3
        self.conv3 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, stride=1, padding=1)
        # After conv3: (128, 16, 16)
        self.pool3 = nn.MaxPool2d(kernel_size=2, stride=2)
        # After pool3: (128, 8, 8)

        # Fully Connected Layers
        # Calculate input features for the first linear layer
        # (128 channels * 8 * 8 spatial dimensions)
        self.fc1 = nn.Linear(128 * 8 * 8, 512)
        self.fc2 = nn.Linear(512, num_classes)

    def forward(self, x):
        # Apply Conv1 -> ReLU -> Pool1
        x = self.pool1(F.relu(self.conv1(x)))
        # Apply Conv2 -> ReLU -> Pool2
        x = self.pool2(F.relu(self.conv2(x)))
        # Apply Conv3 -> ReLU -> Pool3
        x = self.pool3(F.relu(self.conv3(x)))

        # Flatten the output for the fully connected layers
        x = x.view(-1, 128 * 8 * 8)

        # Apply FC1 -> ReLU -> FC2
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

print("SimpleCNN model class defined successfully.")

"""## Train CNN Model on Combined Data

### Subtask:
Implement the training loop for the defined CNN model using a suitable loss function (e.g., CrossEntropyLoss) and optimizer (e.g., Adam). Train the model on the `combined_df` via the DataLoader.

**Reasoning**:
To begin training the CNN model, I will instantiate the `SimpleCNN` model, move it to the appropriate device, and define the `CrossEntropyLoss` loss function and the `Adam` optimizer as specified.
"""

model = SimpleCNN(num_classes=4).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

print(f"Model instantiated on {device}.")
print("Loss function: CrossEntropyLoss")
print("Optimizer: Adam")

"""**Reasoning**:
Now that the model, loss function, and optimizer are initialized, I will implement the training loop to train the CNN model on the combined data, including validation after each epoch, as per the instructions.


"""

num_epochs = 10 # You can adjust the number of epochs

for epoch in range(num_epochs):
    model.train() # Set model to training mode
    running_loss = 0.0
    for i, (inputs, labels) in enumerate(train_dataloader):
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad() # Zero the parameter gradients

        outputs = model(inputs) # Forward pass
        loss = criterion(outputs, labels) # Calculate loss
        loss.backward() # Backward pass
        optimizer.step() # Optimize

        running_loss += loss.item()

    print(f"Epoch {epoch+1}/{num_epochs}, Training Loss: {running_loss/len(train_dataloader):.4f}")

    # Validation phase
    model.eval() # Set model to evaluation mode
    val_loss = 0.0
    correct = 0
    total = 0
    with torch.no_grad(): # Disable gradient calculation for validation
        for inputs, labels in val_dataloader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            val_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    val_accuracy = 100 * correct / total
    print(f"Validation Loss: {val_loss/len(val_dataloader):.4f}, Validation Accuracy: {val_accuracy:.2f}%")

print("Training complete.")

"""## Evaluate CNN Performance on Combined Data

### Subtask:
Evaluate the trained CNN model's performance. Calculate and report the overall accuracy and the F1-score. Include a classification report to show precision, recall, and F1-score for each class.

**Reasoning**:
To evaluate the trained CNN model's performance, I will import the necessary metrics from `sklearn.metrics` to calculate accuracy, F1-score, and generate a classification report.
"""

from sklearn.metrics import accuracy_score, f1_score, classification_report

print("Imported accuracy_score, f1_score, and classification_report from sklearn.metrics.")

"""**Reasoning**:
I will evaluate the trained CNN model's performance by setting it to evaluation mode, collecting true and predicted labels from the validation set, and then calculating and printing the overall accuracy, F1-score, and a detailed classification report.


"""

model.eval() # Set model to evaluation mode
all_labels = []
all_predictions = []

with torch.no_grad(): # Disable gradient calculation
    for inputs, labels in val_dataloader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, predicted = torch.max(outputs.data, 1)

        all_labels.extend(labels.cpu().numpy())
        all_predictions.extend(predicted.cpu().numpy())

# Calculate overall accuracy
overall_accuracy = accuracy_score(all_labels, all_predictions)

# Calculate overall F1-score (weighted to account for class imbalance)
overall_f1_score = f1_score(all_labels, all_predictions, average='weighted')

# Generate classification report
# Assuming labels are 0, 1, 2, 3 as per problem context
target_names = ['Class 0', 'Class 1', 'Class 2', 'Class 3']
classification_rep = classification_report(all_labels, all_predictions, target_names=target_names, zero_division=0)

print(f"\nOverall Accuracy: {overall_accuracy:.4f}")
print(f"Overall F1-Score (Weighted): {overall_f1_score:.4f}")
print("\nClassification Report:")
print(classification_rep)

"""## Final Task

### Subtask:
Summarize the training and evaluation results of the CNN model on the combined dataset, highlighting the accuracy and F1-score achieved and any observations regarding class performance.

## Summary:

### Q&A
The training and evaluation results of the CNN model on the combined dataset show an overall accuracy of 95.26% and an overall weighted F1-score of 95.28%. Performance varies slightly across classes, with Class 1 achieving a perfect 1.00 F1-score, while Class 0 has the lowest F1-score at 0.91.

### Data Analysis Key Findings
*   The CNN model was trained over 10 epochs. The training loss consistently decreased from approximately 0.8346 (Epoch 1) to 0.0521 (Epoch 10).
*   Validation accuracy improved significantly throughout training, starting at 63.73% (Epoch 1) and reaching a peak of 95.26% by Epoch 10.
*   The final evaluation on the validation set showed an overall accuracy of 0.9526 (95.26%) and an overall weighted F1-score of 0.9528 (95.28%).
*   Class-wise performance from the classification report indicates:
    *   **Class 1** demonstrated exceptional performance with a Precision, Recall, and F1-score of 1.00.
    *   **Class 2** and **Class 3** also performed very well, with F1-scores of 0.96 and 0.94, respectively.
    *   **Class 0** had slightly lower performance compared to others, with an F1-score of 0.91 (Precision: 0.88, Recall: 0.94).

### Insights or Next Steps
*   The model demonstrates strong classification capabilities for the given dataset, with high overall accuracy and F1-score.
*   Investigate the samples belonging to Class 0 to understand potential reasons for its slightly lower performance compared to other classes. This could involve reviewing image quality, feature commonality, or potential mislabeling within this specific class.

# Task
Generate and display a confusion matrix using the `all_labels` (true labels) and `all_predictions` (predicted labels) from the validation set, and summarize the insights gained from this confusion matrix regarding the classification performance and any specific strengths or weaknesses for each class.

## Generate Confusion Matrix

### Subtask:
Generate and display a confusion matrix based on the true labels and predicted labels from the validation set.

**Reasoning**:
To generate and display the confusion matrix, I will import the necessary functions `confusion_matrix` and `ConfusionMatrixDisplay` from `sklearn.metrics`, along with `matplotlib.pyplot` for plotting.
"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

print("Imported confusion_matrix, ConfusionMatrixDisplay from sklearn.metrics and matplotlib.pyplot.")

"""**Reasoning**:
Now that the necessary libraries are imported, I will create the confusion matrix, instantiate a `ConfusionMatrixDisplay` object, and plot the confusion matrix with a title to visualize the model's classification performance.


"""

cm = confusion_matrix(all_labels, all_predictions)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=target_names)
disp.plot(cmap='Blues')
plt.title('Confusion Matrix for CNN Model')
plt.show()

"""### Summary of Confusion Matrix Insights

The confusion matrix visually confirms the strong performance of the CNN model, particularly for **Class 1 (Minority Class)**, which shows 198 correct predictions out of 198 actual instances, with no misclassifications. This indicates that the GAN-based data augmentation effectively balanced this class, allowing the model to learn its features distinctly.

For **Class 2**, the model made 505 correct predictions, with only 9 instances mistakenly classified as Class 0 and 16 as Class 3. Similarly, for **Class 3**, there were 327 correct predictions, with 9 misclassified as Class 0 and 15 as Class 2.

The most notable area for improvement appears to be **Class 0**. While 136 instances were correctly identified, 4 were misclassified as Class 2 and 5 as Class 3. Although these numbers are small in absolute terms, they are significant relative to the class size, suggesting that Class 0 still presents some challenges for the model, possibly due to similarities with other classes or inherent complexities in its features.

Overall, the confusion matrix reinforces the high accuracy and F1-score observed in the classification report, demonstrating the model's ability to differentiate between the classes, with a particularly successful outcome for the previously underrepresented minority class.

## Final Task

### Subtask:
Summarize the training and evaluation results of the CNN model on the combined dataset, highlighting the accuracy and F1-score achieved and any observations regarding class performance.

## Summary:

### Q&A
The confusion matrix reveals strong classification performance overall. Class 1 (Minority Class) shows exceptional performance with 198 correct predictions out of 198 actual instances, indicating no misclassifications. Class 2 correctly predicted 505 instances, with minor misclassifications to Class 0 (9) and Class 3 (16). Similarly, Class 3 made 327 correct predictions, with 9 misclassified as Class 0 and 15 as Class 2. The main area for improvement is Class 0, where 136 instances were correctly identified, but 4 were misclassified as Class 2 and 5 as Class 3, which is relatively significant given its class size.

### Data Analysis Key Findings
*   A confusion matrix was successfully generated and displayed, visualizing the CNN model's classification performance.
*   The model exhibited strong performance for Class 1 (Minority Class), with 198 out of 198 instances correctly classified and no misclassifications.
*   For Class 2, the model achieved 505 correct predictions, with only 9 instances misclassified as Class 0 and 16 as Class 3.
*   Class 3 showed 327 correct predictions, with 9 instances misclassified as Class 0 and 15 as Class 2.
*   Class 0 was identified as the primary area for improvement, with 136 correct predictions but 4 misclassified as Class 2 and 5 as Class 3, suggesting some challenges for this class.

### Insights or Next Steps
*   The successful classification of Class 1 (Minority Class) with no errors highlights the effectiveness of the GAN-based data augmentation in balancing this class and improving the model's ability to learn its distinct features.
*   Further investigation into the misclassifications for Class 0 could involve analyzing the features of the misclassified instances to understand common patterns or similarities with other classes, potentially leading to targeted feature engineering or additional data augmentation for this specific class.
"""

# ==============================================================================
# --- SAVE MODEL WEIGHTS FOR DEPLOYMENT ---
# This block saves the trained SimpleCNN weights so the FastAPI backend can
# load them via app/backend/model.py.
# The file is saved to Google Drive for easy download.
# ==============================================================================
import os

save_dir = "/content/drive/MyDrive/NeuroGAN_exports"
os.makedirs(save_dir, exist_ok=True)
save_path = os.path.join(save_dir, "cnn_alzheimer.pt")

torch.save({
    "model_state_dict": model.state_dict(),
    "class_names": ["NonDemented", "VeryMildDemented", "MildDemented", "ModerateDemented"],
    "class_mapping": {0: "NonDemented", 1: "VeryMildDemented", 2: "MildDemented", 3: "ModerateDemented"},
    "accuracy": overall_accuracy,
    "f1_score": overall_f1_score,
    "architecture": "SimpleCNN-3conv-64x64",
    "input_size": (1, 64, 64),
}, save_path)

print(f"\n✅ Model saved to: {save_path}")
print(f"   Accuracy: {overall_accuracy:.4f} | F1: {overall_f1_score:.4f}")
print(f"\nDownload from Google Drive and place at:")
print(f"   NeuroGAN/model_weights/cnn_alzheimer.pt")
print(f"\nModel architecture:")
print(model)